[package]
authors = ["David Karwowski <karwowski.david@gmail.com>"]
name = "blinkyf7"
version = "0.1.0"

[dependencies]
#cortex-m = "0.3.0"
cortex-m = "0.3.1"
cortex-m-rt = "0.3.5"
cortex-m-semihosting = "0.2.0"
cortex-m-rtfm = "0.2.0"

[dev-dependencies.cortex-m-rt]
features = ["abort-on-panic"]
version = "0.3.5"

[dependencies.stm32f7x]
path = "../lib/stm32f7x"
features = ["rt"]

[dependencies.f7]
path = "../lib/f7"

